spring:
  profiles:
    active:
      - gcp

file-storage:
  logFileTypeToInfoMap:
    CAR_LOG:
      fileNameFormat: car_log_%d.csv
      path: car-logs
    CAR_ERROR_LOG:
      fileNameFormat: car_log_%d.txt
      path: car-error-logs
