spring:
  datasource:
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  cloud:
    gcp:
      project-id: obd-services-251511
      sql:
        instance-connection-name: obd-services-251511:europe-west1:obd-services-backend
        database-name: obd

  security:
    basic:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

google:
  storage:
    bucket-name:
      obd-services-251511.appspot.com

pub-sub:
  subscription-name: car-log-sub
  enabled: false