spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gcp:
      sql:
        instance-connection-name: obd-services:europe-west1:obd-services-sql-db
        database-name: obd-backend-db
  security:
    basic:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    datasource:
      url: jdbc:mysql://146.148.21.29:3306/obd-backend-db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
