spring:
  cloud:
    gcp:
      sql:
        instance-connection-name: obd-services:europe-west1:obd-services-sql-db
        database-name: obd-backend-db
  security:
    basic:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
