spring:
  security:
    basic:
      enabled: false
  jpa:
    database-platform:
      org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://35.233.86.171/obd
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
